/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [ './assets/src/**/*.{js,jsx}' ],
	theme: {
		extend: {
			colors: {
				'browser-bar': '#FAFAFA',
				accent: '#2271B1',
				'accent-secondary': '#2563EB',
				'accent-wp-primary': '#0073AA',
				'accent-wp-primary-alt': '#70CFFF',
				'accent-wp-secondary': '#00A0D2',
				'heading-text': '#030712',
				'body-text': '#374151',
				'hover-wp-default': '#135E96',
				'secondary-text': '#9CA3AF',
				'disabled-text': '#D1D5DB',
				'nav-active': '#111827',
				'nav-inactive': '#374151',
				'background-primary': '#FFFFFF',
				'background-secondary': '#F3F4F6',
				'background-tertiary': '#F0F0FF',
				'border-primary': '#D1D5DB',
				'border-secondary': '#6B7280',
				'border-tertiary': '#D8DFE9',
				'icon-primary': '#5A03EF',
				'icon-secondary': '#374151',
				'alert-info': '#3B82F6',
				'alert-info-bg': '#EFF6FF',
				'alert-info-text': '#3D4592',
				'alert-success': '#22C55E',
				'alert-success-bg': '#F0FDF4',
				'alert-success-text': '#16a34a',
				'alert-warning': '#FACC15',
				'alert-warning-bg': '#FEFCE8',
				'alert-warning-text': '#ca8a04',
				'alert-error': '#EF4444',
				'alert-error-bg': '#FEF2F2',
				'alert-error-text': '#dc2626',
				favorite: '#FD3997',
				tooltip: '#334155',
				'credit-warning': '#FB7E0A',
				'button-bg': '#2F327E',
				'credit-danger': '#EA1522',
				'button-disabled': '#E5E7EB',
				'blue-crayola': '#3D4592',
				'zip-body-text': '#475569',
				'zip-app-highlight-bg': '#F6FAFE',
				'zip-app-heading': '#0F172A',
				'zip-dark-theme-heading': '#FCFCFD',
				'zip-dark-theme-content-background': '#27313F',
				'zip-dark-theme-body': '#E4EAF1',
				'zip-dark-theme-border': '#333E52',
				'zip-dark-theme-icon-active': '#BCC9DC',
				'zip-dark-theme-bg': '#1F2733',
				'zip-light-border-primary': '#E5E7EB',
				'zip-app-border-hover': '#D1DAE5',
				'gradient-color-1': '#B809A7',
				'gradient-color-2': '#E90B76',
				'gradient-color-3': '#FC8536',
				'step-gradient':
					'linear-gradient(to bottom, #FFF 0%, #0000FF 100%)',
				'zip-app-inactive-icon': '#94A3B8',
				'zip-app-light-bg': '#F0F4FA',
				'st-background-secondary': '#f7f7f9',
				'outline-color': '#FF580E',
				'preview-background': '#F2F4F7',
				'wp-background': '#F6F7F7',
				'wp-border': '#DCDCDE',
				'wp-component-border': '#8C8F94',
			},
			fontFamily: {
				sans: [
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'Segoe UI',
					'Roboto',
					'Oxygen',
					'Ubuntu',
					'Cantarell',
					'Fira Sans',
					'Droid Sans',
					'Helvetica Neue',
					'sans-serif',
				],
			},
		},
	},
	plugins: [],
	corePlugins: {
		preflight: false,
	},
	important: '.ast-attachments-browser',
};
